spring:
  application:
    name: ai-customer-support

  datasource:
    url: jdbc:postgresql://localhost:5432/supportdb
    username: postgres
    password: CUBO1212CUBO1212

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

jwt:
  secret: una-clave-secreta-larga-segura-y-temporal
  expiration: 3600000
